"""Add expiration fields to Message model

Revision ID: 2c896968722b
Revises: 82bd4894978a
Create Date: 2024-10-22 16:40:21.263549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c896968722b'
down_revision = '82bd4894978a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expiration_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('expiration_minutes')
        batch_op.drop_column('expiration_hours')
        batch_op.drop_column('expiration_days')

    # ### end Alembic commands ###
